export const getPageLink = (t) => [
  {
    id: 1,
    searchname: t("dataname.arxivhujjatlari"),
    link: "archivedDocuments/royxat",
    name: t("dataname.manbalar"),
  },
  {
    id: 2,
    searchname: t("dataname.matbuot"),
    link: "press/tarix",
    name: t("dataname.manbalar"),
  },
  {
    id: 3,
    searchname: t("dataname.asarlar"),
    link: "research/asarlar",
    name: t("dataname.maqolalar"),
  },
  {
    id: 4,
    searchname: t("dataname.maqolalar"),
    link: "research/maqolalar",
    name: t("dataname.izlanishlar"),
  },
  {
    id: 5,
    searchname: t("dataname.dissertatsiyalar"),
    link: "research/dissertatsiyalar",
    name: t("dataname.izlanishlar"),
  },
  {
    id: 6,
    searchname: t("dataname.esdaliklar"),
    link: "research/esdaliklar",
    name: t("dataname.izlanishlar"),
  },
  {
    id: 7,
    searchname: t("dataname.asarlar"),
    link: "languageSpelling/asarlar",
    name: t("dataname.til_va_imlo"),
  },
  {
    id: 8,
    searchname: t("dataname.maqolalar"),
    link: "languageSpelling/maqolalar",
    name: t("dataname.til_va_imlo"),
  },
  {
    id: 9,
    searchname: t("dataname.hikmatlar"),
    link: "languageSpelling/hikmatlar",
    name: t("dataname.til_va_imlo"),
  },
  {
    id: 10,
    searchname: t("dataname.asarlar"),
    link: "turkistan/asarlar",
    name: t("dataname.turkiston_muxtoriyati"),
  },
  {
    id: 11,
    searchname: t("dataname.maqolalar"),
    link: "turkistan/maqolalar",
    name: t("dataname.turkiston_muxtoriyati"),
  },
  {
    id: 12,
    searchname: t("dataname.sherlar"),
    link: "turkistan/sherlar",
    name: t("dataname.turkiston_muxtoriyati"),
  },
  {
    id: 13,
    searchname: t("dataname.esdaliklar"),
    link: "turkistan/esdaliklar",
    name: t("dataname.turkiston_muxtoriyati"),
  },
  {
    id: 14,
    searchname: t("dataname.yangiliklar"),
    link: "eventsList/yangiliklar",
    name: t("dataname.voqealar"),
  },
  {
    id: 15,
    searchname: t("dataname.yiginlar"),
    link: "eventsList/yiginlar",
    name: t("dataname.voqealar"),
  },
  {
    id: 16,
    searchname: t("dataname.seminarlar"),
    link: "eventsList/seminarlar",
    name: t("dataname.voqealar"),
  },
  {
    id: 17,
    searchname: t("dataname.suratlar"),
    link: "suratlar",
    name: t("dataname.kor_eshit_oqi"),
  },
  {
    id: 18,
    searchname: t("dataname.koruvlar"),
    link: "koruvlar/id",
    name: t("dataname.kor_eshit_oqi"),
  },
  {
    id: 19,
    searchname: t("dataname.eshituvlar"),
    link: "eshituvlar",
    name: t("dataname.kor_eshit_oqi"),
  },
];
